# Generated by Django 4.1 on 2023-03-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_codigorecuperacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigorecuperacao',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
